# Generated by Django 4.2 on 2023-04-27 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_auto_20220302_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Adhar',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
