# Generated by Django 4.2 on 2023-04-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0008_alter_employees_adhar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Adhar',
        ),
    ]
