# Generated by Django 4.2 on 2023-04-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0009_remove_employees_adhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='aadhaar_number',
            field=models.CharField(default='', max_length=12),
        ),
    ]
